import { Injectable } from '@angular/core';

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, BehaviorSubject } from 'rxjs';
import { environment } from '../../environments/environment';

@Injectable({
    providedIn: 'root'
})
export class dataService {

    public books = [];
    public users: any;
    constructor(private httpClient: HttpClient) { }


    getClients(vendedor_id: any) {
        vendedor_id = 501;
        // const headers = new HttpHeaders().set('Content-type', 'application/json');
        // return this.httpClient.post(environment.AUTH_SERVER_ADDRESS + '/lista/cliente', {
        //     vendedor_id: vendedor_id
        // },
        //     { headers: headers }
        // );
        let clients = [
            {
                "cli_id": 1306032792,
                "vendedor_id": 501,
                "cli_fantasia": "MARCUS",
                "cli_razaosocial": "MARCUS MOREIRA",
                "cli_endereco": "LUIZ COUTINHO CAVALCANTI 121",
                "cli_bairro": "GUADALUPE",
                "cli_codigocidade": 282,
                "cli_cep": "21675310",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "01306032792",
                "cli_inscricaoestadual": "",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "MARCUS",
                "cli_contato2": "",
                "cli_telefone1": "21993973833",
                "cli_telefone2": "",
                "cli_vip": null,
                "cli_homepage": null,
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "LUIZ COUTINHO",
                "cli_bairroentrega": "GUADALUPE",
                "cli_cepentrega": "21675310",
                "cli_codigocidadeentrega": null,
                "categoria_id": null,
                "atividade_id": 36,
                "tabela_id": null,
                "condicaopagto_id": null,
                "formapagto_id": null,
                "responsavel_id": null,
                "credito_bloqueado": null,
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": null,
                "trava_limite_credito": false
            },
            {
                "cli_id": 1,
                "vendedor_id": 501,
                "cli_fantasia": "MARIA PAULA BITTENCOURT TENORIO.",
                "cli_razaosocial": "INATIVO ---MARIA PAULA BITTENCOURT TENOR",
                "cli_endereco": "R. MARAPENDI,27",
                "cli_bairro": "MARECHAL HERMES",
                "cli_codigocidade": 282,
                "cli_cep": "25030040",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "44366620715",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02133488621",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. MARAPENDI,27",
                "cli_bairroentrega": "MARECHAL HERMES",
                "cli_cepentrega": "25030040",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 9,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 2,
                "vendedor_id": 501,
                "cli_fantasia": "ACOUGUE FOLIBELO LTDA.",
                "cli_razaosocial": "INATIVO--ACOUGUE FOLIBELO LTDA.",
                "cli_endereco": "R. EXPEDICIONARIO DE ARAUJO,482",
                "cli_bairro": "ENGENHO DO PORTO",
                "cli_codigocidade": 282,
                "cli_cep": "2508090",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "J",
                "cli_cnpjcpf": "27173558000125",
                "cli_inscricaoestadual": "82803580",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02127713226",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. EXPEDICIONARIO DE ARAUJO,482",
                "cli_bairroentrega": "ENGENHO DO PORTO",
                "cli_cepentrega": "2508090",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 1,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 3,
                "vendedor_id": 501,
                "cli_fantasia": "MARIA ODETE.",
                "cli_razaosocial": "MARIA ODETE.",
                "cli_endereco": "ESTR. RODRIGUES CALDAS,1491",
                "cli_bairro": "CURICICA",
                "cli_codigocidade": 282,
                "cli_cep": "22710561",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "01453523740",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "021-2446.5605",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR. RODRIGUES CALDAS,1491",
                "cli_bairroentrega": "CURICICA",
                "cli_cepentrega": "22710561",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 14,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 4,
                "vendedor_id": 501,
                "cli_fantasia": "ACOUGUE FLOR DO MATO ALTO LTDA-ME.",
                "cli_razaosocial": "ACOUGUE FLOR DO MATO ALTO LTDA-ME.",
                "cli_endereco": "R. CANDIDO BENICIO,2953",
                "cli_bairro": "PCA SECA",
                "cli_codigocidade": 282,
                "cli_cep": "0",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "J",
                "cli_cnpjcpf": "33234253000189",
                "cli_inscricaoestadual": "82150242",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "DOMINGOS",
                "cli_contato2": "",
                "cli_telefone1": "02133921143",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. CANDIDO BENICIO,2953",
                "cli_bairroentrega": "PCA SECA",
                "cli_cepentrega": "0",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 1,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 9,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 5,
                "vendedor_id": 501,
                "cli_fantasia": "SOCIEDADE COOPER IMOVEIS CHEF RIO LTDA.",
                "cli_razaosocial": "SOCIEDADE COOPER IMOVEIS CHEF RIO LTDA.",
                "cli_endereco": "AV. PRES. WILSON- S/406 AP.409,164",
                "cli_bairro": "CASTELO",
                "cli_codigocidade": 282,
                "cli_cep": "20030020",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "00618229000194",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02124534026  ",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "AV. PRES. WILSON- S/406 AP.409,164",
                "cli_bairroentrega": "CASTELO",
                "cli_cepentrega": "20030020",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 6,
                "vendedor_id": 501,
                "cli_fantasia": "ACOUGUE PALACIO DA PENHA LTDA.",
                "cli_razaosocial": "INATIVO--ACOUGUE PALACIO DA PENHA LTDA.",
                "cli_endereco": "R. JOSE RUCAS,1025",
                "cli_bairro": "PENHA",
                "cli_codigocidade": 282,
                "cli_cep": "21070370",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "J",
                "cli_cnpjcpf": "01988903000195",
                "cli_inscricaoestadual": "85846943",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02125902512 021",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. JOSE RUCAS,1025",
                "cli_bairroentrega": "PENHA",
                "cli_cepentrega": "21070370",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 1,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 7,
                "vendedor_id": 501,
                "cli_fantasia": "ADEMAR LUIZ DE FARIAS.",
                "cli_razaosocial": "ADEMAR LUIZ DE FARIAS.",
                "cli_endereco": "R. JOAO REGO,363",
                "cli_bairro": "OLARIA",
                "cli_codigocidade": 282,
                "cli_cep": "21073160",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "02838153000138",
                "cli_inscricaoestadual": "81208804",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "APARECIDA",
                "cli_contato2": "",
                "cli_telefone1": "02122307964 021",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. JOAO REGO,363",
                "cli_bairroentrega": "OLARIA",
                "cli_cepentrega": "21073160",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 8,
                "vendedor_id": 501,
                "cli_fantasia": "INATIVO-ADRIANA AZEVEDO DOS SANTOS.",
                "cli_razaosocial": "INATIVO-ADRIANA AZEVEDO DOS SANTOS.",
                "cli_endereco": "R. ENGENHEIRO ASSIS RIBEIRO,80",
                "cli_bairro": "BENTO RIBEIRO",
                "cli_codigocidade": 282,
                "cli_cep": "",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "06914725721",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02130119236 021",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. ENGENHEIRO ASSIS RIBEIRO,80",
                "cli_bairroentrega": "BENTO RIBEIRO",
                "cli_cepentrega": "",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 7,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 9,
                "vendedor_id": 501,
                "cli_fantasia": "ADRIANA FARIAS BRANDAO(INATIVO)",
                "cli_razaosocial": "INATIVO--ADRIANA FARIAS BRANDAO.",
                "cli_endereco": "ESTR. JOSE RUCAS,1361",
                "cli_bairro": "PENHA",
                "cli_codigocidade": 282,
                "cli_cep": "25080090",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "01095140760",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02138818840",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR. JOSE RUCAS,1361",
                "cli_bairroentrega": "PENHA",
                "cli_cepentrega": "25080090",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 10,
                "vendedor_id": 501,
                "cli_fantasia": "ELAINE LILK.",
                "cli_razaosocial": "ELAINE LILK.",
                "cli_endereco": "ESTR.RODRIGUES CALDAS -CASA 78,2228",
                "cli_bairro": "CURICICA",
                "cli_codigocidade": 282,
                "cli_cep": "",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "75470772772",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02124463506  ",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR.RODRIGUES CALDAS -CASA 78,2228",
                "cli_bairroentrega": "CURICICA",
                "cli_cepentrega": "",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 9,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 11,
                "vendedor_id": 501,
                "cli_fantasia": "AGROPECUARIA E RACOES FEITOSA LTDA.",
                "cli_razaosocial": "BAZAR E RACOES JU FEITOSA LTDA.",
                "cli_endereco": "ESTR. DO PAU FERRO,41",
                "cli_bairro": "PECHINCHA",
                "cli_codigocidade": 282,
                "cli_cep": "22743210",
                "cli_fax": "",
                "cli_email": "PETSHOUSE.PETSHOP@GMAIL.COM",
                "cli_pessoafj": "J",
                "cli_cnpjcpf": "00227613000166",
                "cli_inscricaoestadual": "85479679",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "CELI",
                "cli_contato2": "",
                "cli_telefone1": "0212425.5862",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR. DO PAU FERRO,41",
                "cli_bairroentrega": "PECHINCHA",
                "cli_cepentrega": "22743210",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 1,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 4,
                "formapagto_id": 1,
                "responsavel_id": 9,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 12,
                "vendedor_id": 501,
                "cli_fantasia": "AILSON DANIEL PESSOA.",
                "cli_razaosocial": "AILSON DANIEL PESSOA.",
                "cli_endereco": "R. NOVA CANAAM,33",
                "cli_bairro": "BONSUCESSO",
                "cli_codigocidade": 282,
                "cli_cep": "",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "02340508452",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "",
                "cli_contato2": "",
                "cli_telefone1": "02139775636  ",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "R. NOVA CANAAM,33",
                "cli_bairroentrega": "BONSUCESSO",
                "cli_cepentrega": "",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 7,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 13,
                "vendedor_id": 501,
                "cli_fantasia": "ALBINO CASTRO MARTINS.",
                "cli_razaosocial": "ALBINO CASTRO MARTINS.",
                "cli_endereco": "ESTR. DA SOCA,226",
                "cli_bairro": "TAQUARA",
                "cli_codigocidade": 282,
                "cli_cep": "",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "24550507772",
                "cli_inscricaoestadual": "00000",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "NALVA",
                "cli_contato2": "",
                "cli_telefone1": "02124404400  ",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR. DA SOCA,226",
                "cli_bairroentrega": "TAQUARA",
                "cli_cepentrega": "",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 5,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            },
            {
                "cli_id": 14,
                "vendedor_id": 501,
                "cli_fantasia": "INATIVO-ALCAPAO AVICULTORA RACOES LTDA.",
                "cli_razaosocial": "INATIVO-ALCAPAO AVICULTORA RACOES LTDA.",
                "cli_endereco": "ESTR. DO GALEAO,2715",
                "cli_bairro": "ILHA DO GOVERNADOR",
                "cli_codigocidade": 282,
                "cli_cep": "",
                "cli_fax": "",
                "cli_email": "",
                "cli_pessoafj": "F",
                "cli_cnpjcpf": "42208595000115",
                "cli_inscricaoestadual": "81904162",
                "cli_inscricaomunicipal": "",
                "cli_contato1": "EDUARDO",
                "cli_contato2": "",
                "cli_telefone1": "02133934344  ",
                "cli_telefone2": "",
                "cli_vip": "N",
                "cli_homepage": "",
                "cli_limitecredito": "0.00",
                "cli_totaltitulosvencidos": "0.00",
                "cli_totaltitulosavencer": "0.00",
                "cli_saldo": "0.00",
                "cli_enderecoentrega": "ESTR. DO GALEAO,2715",
                "cli_bairroentrega": "ILHA DO GOVERNADOR",
                "cli_cepentrega": "",
                "cli_codigocidadeentrega": 282,
                "categoria_id": 2,
                "atividade_id": 32,
                "tabela_id": 1,
                "condicaopagto_id": 7,
                "formapagto_id": 1,
                "responsavel_id": 8,
                "credito_bloqueado": "N",
                "observacao": "",
                "atualizar_android": true,
                "cliente_novo": false,
                "dia_visita": "",
                "trava_limite_credito": false
            }
        ];
        return clients;

    }
    getProdutos(vendedor_id: any) {
        vendedor_id = 501;
        let Produtos = [{
            "produto_id": 10001,
            "vendedor_id": 501,
            "descricaoproduto": "PITUKAO 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "107.29",
            "custo": "59.00",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "107.29",
            "desc_maximopercentual": "25.00",
            "inf_marca": "",
            "inf_produto": "",
            "comissoes": "",
            "tabelas": "1-107,29",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10002,
            "vendedor_id": 501,
            "descricaoproduto": "PITUKAO 15KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "65.07",
            "custo": "34.50",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "65.07",
            "desc_maximopercentual": "25.00",
            "inf_marca": "",
            "inf_produto": "",
            "comissoes": "",
            "tabelas": "1-65,07",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10005,
            "vendedor_id": 501,
            "descricaoproduto": "PITUKINHA 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "130.96",
            "custo": "68.00",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "130.96",
            "desc_maximopercentual": "25.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-130,96",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10006,
            "vendedor_id": 501,
            "descricaoproduto": "PITUKINHA 7KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "36.18",
            "custo": "23.00",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "36.18",
            "desc_maximopercentual": "25.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-36,18",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10008,
            "vendedor_id": 501,
            "descricaoproduto": "SHOW DOG 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "97.41",
            "custo": "68.19",
            "codigobarras": "",
            "estoque_offline": "6",
            "obs": "",
            "produtoemfalta": "N",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "97.41",
            "desc_maximopercentual": "25.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-97,41",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10009,
            "vendedor_id": 501,
            "descricaoproduto": "SHOW DOG 15KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "58.44",
            "custo": "40.91",
            "codigobarras": "",
            "estoque_offline": "29",
            "obs": "",
            "produtoemfalta": "N",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "58.44",
            "desc_maximopercentual": "25.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-58,44",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10010,
            "vendedor_id": 501,
            "descricaoproduto": "SHOW DOG 7KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "27.28",
            "custo": "19.09",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "27.28",
            "desc_maximopercentual": "25.00",
            "inf_marca": "",
            "inf_produto": "",
            "comissoes": "",
            "tabelas": "1-27,28",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10012,
            "vendedor_id": 501,
            "descricaoproduto": "DOG SHOW FILHOTE 7KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "31.66",
            "custo": "21.80",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "31.66",
            "desc_maximopercentual": "25.00",
            "inf_marca": "",
            "inf_produto": "",
            "comissoes": "",
            "tabelas": "1-31,66",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10017,
            "vendedor_id": 501,
            "descricaoproduto": "FOSTER PREMIUM 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "108.57",
            "custo": "76.00",
            "codigobarras": "",
            "estoque_offline": "42",
            "obs": "",
            "produtoemfalta": "N",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "108.57",
            "desc_maximopercentual": "30.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-108,57",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10018,
            "vendedor_id": 501,
            "descricaoproduto": "FOSTER PREMIUM 15KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "65.15",
            "custo": "45.61",
            "codigobarras": "",
            "estoque_offline": "161",
            "obs": "",
            "produtoemfalta": "N",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "65.15",
            "desc_maximopercentual": "30.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-65,15",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10019,
            "vendedor_id": 501,
            "descricaoproduto": "FOSTER PREMIUM 7KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "30.40",
            "custo": "21.67",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "30.40",
            "desc_maximopercentual": "30.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-30,40",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10020,
            "vendedor_id": 501,
            "descricaoproduto": "FOSTER MIX 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "115.27",
            "custo": "66.50",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "115.27",
            "desc_maximopercentual": "30.00",
            "inf_marca": "",
            "inf_produto": "",
            "comissoes": "",
            "tabelas": "1-115,27",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },
        {
            "produto_id": 10021,
            "vendedor_id": 501,
            "descricaoproduto": "FOSTER JUNIOR 25KG",
            "embalagem": "SC",
            "qtde_minimo_venda": "1.00",
            "precopadrao": "121.02",
            "custo": "84.71",
            "codigobarras": "",
            "estoque_offline": "0",
            "obs": "",
            "produtoemfalta": "S",
            "produtonovo": "N",
            "produtoempromocao": "N",
            "data_inicio_promocao": "2020-06-15 00:00:00",
            "data_fim_promocao": "2020-06-15 00:00:00",
            "quant_minima_promocao": "1.00",
            "preco_promocao": "121.02",
            "desc_maximopercentual": "30.00",
            "inf_marca": "NUTRIARA",
            "inf_produto": "RACAO PARA CAO",
            "comissoes": "",
            "tabelas": "1-121,02",
            "dados_adicionais": "",
            "produtoembalagem": 0
        },];
        return Produtos;

    }
     getTitulos(vendedor_id: any) {
        vendedor_id = 501;
        let titulos = [{
            "contador": 11677581,
            "cliente_id": 22578,
            "vendedor_id": 501,
            "responsavel_id": 34,
            "numerotitulo": 799,
            "parcela": "1-1",
            "dataemissao": "2020-05-25 00:00:00",
            "datavencimento": "2020-06-09 00:00:00",
            "valor": "3537.50",
            "saldo": "0.00",
            "juros": "35.38",
            "cliente_nome": "PETSISTER RACOES LTDA",
            "cliente_contato": "",
            "cliente_fone": "34067658"
        },
        {
            "contador": 11677582,
            "cliente_id": 22578,
            "vendedor_id": 501,
            "responsavel_id": 34,
            "numerotitulo": 798,
            "parcela": "1-1",
            "dataemissao": "2020-05-25 00:00:00",
            "datavencimento": "2020-06-09 00:00:00",
            "valor": "3617.28",
            "saldo": "0.00",
            "juros": "36.17",
            "cliente_nome": "PETSISTER RACOES LTDA",
            "cliente_contato": "",
            "cliente_fone": "34067658"
        },
        {
            "contador": 11677583,
            "cliente_id": 921,
            "vendedor_id": 501,
            "responsavel_id": 1,
            "numerotitulo": 82584,
            "parcela": "1-1",
            "dataemissao": "2020-04-27 00:00:00",
            "datavencimento": "2020-05-26 00:00:00",
            "valor": "460.18",
            "saldo": "0.00",
            "juros": "17.49",
            "cliente_nome": "EUNICE LEAL DE OLIVEIRA COMERCIO DE RACO",
            "cliente_contato": "",
            "cliente_fone": "0212693.5678"
        },
        {
            "contador": 11677584,
            "cliente_id": 663,
            "vendedor_id": 501,
            "responsavel_id": 34,
            "numerotitulo": 83227,
            "parcela": "1-1",
            "dataemissao": "2020-06-01 00:00:00",
            "datavencimento": "2020-06-16 00:00:00",
            "valor": "177.45",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "CEZARAO PROD. AGROPECUARIOS LTDA.",
            "cliente_contato": "MARCIO",
            "cliente_fone": "0213395.4382"
        },
        {
            "contador": 11677585,
            "cliente_id": 12602,
            "vendedor_id": 501,
            "responsavel_id": 34,
            "numerotitulo": 83226,
            "parcela": "1-1",
            "dataemissao": "2020-06-01 00:00:00",
            "datavencimento": "2020-06-16 00:00:00",
            "valor": "211.80",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "M. A. CORREIA RACOES PROD. AGROPECUARIA",
            "cliente_contato": "",
            "cliente_fone": "0212695.0472377"
        },
        {
            "contador": 11677586,
            "cliente_id": 19313,
            "vendedor_id": 501,
            "responsavel_id": 24,
            "numerotitulo": 19168,
            "parcela": "1-1",
            "dataemissao": "2020-05-29 00:00:00",
            "datavencimento": "2020-06-16 00:00:00",
            "valor": "342.20",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "ANDRE DA SILVA SOARES",
            "cliente_contato": "ANDRE",
            "cliente_fone": "22011659"
        },
        {
            "contador": 11677587,
            "cliente_id": 21229,
            "vendedor_id": 501,
            "responsavel_id": 30,
            "numerotitulo": 19092,
            "parcela": "1-1",
            "dataemissao": "2020-05-25 00:00:00",
            "datavencimento": "2020-06-16 00:00:00",
            "valor": "318.59",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "PET SHOP MATOSO EIRELI",
            "cliente_contato": "",
            "cliente_fone": "25044282"
        },
        {
            "contador": 11677588,
            "cliente_id": 1924,
            "vendedor_id": 501,
            "responsavel_id": 13,
            "numerotitulo": 19343,
            "parcela": "1-1",
            "dataemissao": "2020-06-15 00:00:00",
            "datavencimento": "2020-06-30 00:00:00",
            "valor": "208.32",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "MONIKA BURKARDT.",
            "cliente_contato": "",
            "cliente_fone": "0212275.0358"
        },
        {
            "contador": 11677589,
            "cliente_id": 1739,
            "vendedor_id": 501,
            "responsavel_id": 1,
            "numerotitulo": 19238,
            "parcela": "1-1",
            "dataemissao": "2020-06-03 00:00:00",
            "datavencimento": "2020-06-18 00:00:00",
            "valor": "230.17",
            "saldo": "0.00",
            "juros": "0.00",
            "cliente_nome": "ARI COTA.",
            "cliente_contato": "ANDREIA",
            "cliente_fone": "0212655.4202"
        },];
        return titulos;
    }
}